apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: cs-vikash-test 
  namespace: dev
spec:
  id: cs-vikash-test
  compositionSelector:
    matchLabels:
      provider: azure-official
      cluster: aks
  parameters:
    nodeSize: medium #(small, medium, large)
    minNodeCount: 1 # (1-10)
    version: 1.25.5 # (1.24.9, 1.24.10, 1.25.5, 1.25.6, 1.26.0, 1.26.3, 1.27.1)


