apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: cluster_claim_name 
  namespace: dev
spec:
  id: cluster_name
  compositionSelector:
    matchLabels:
      provider: azure-official
      cluster: aks
  parameters:
    nodeSize: node_size #(small, medium, large)
    minNodeCount: nodecount # (1-10)
    version: k8s_version # (1.25.6, 1.25.11, 1.26.3, 1.26.6, 1.27.1, 1.27.3, 1.28.0)


